#!/usr/bin/env python3
"""Check the site: nothing stale, and no link that goes nowhere.

    python3 tools/verify/test_site.py

Two things are checked, and the second is the one that earns its keep.

**Stale.** `docs/*.html` is generated by `tools/site/build.py`. Rebuild it into
a temporary directory and byte-compare, exactly as the pictures are checked —
because a hand-edit to a generated page is silently discarded the next time
anybody runs the generator, and the person it misleads is whoever trusted the
page in between.

**Dead links.** Every relative `href` and `src` on every page must resolve to a
file that exists. A multi-page site is mostly links, and a link that 404s over
GitHub Pages does not 404 on your disk — `docs/guide/step-12.html` is a missing
file either way, but a typo in a media path fails only for the reader. Cheap to
check, and it catches the mistake that a screenshot never shows: the page you
looked at was the one that worked.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DOCS = os.path.join(ROOT, "docs")

fails = []


def check(name, ok, detail=""):
    print(f"  {'ok  ' if ok else 'FAIL'}  {name:<58} {'' if ok else detail}")
    if not ok:
        fails.append(name)


def links(text):
    """Every href/src in a page. Not an HTML parser and does not need to be:
    the pages are generated, so the quoting is uniform."""
    return re.findall(r'(?:href|src)="([^"]+)"', text)


def main():
    print("the site is generated, and every link resolves")
    tmp = tempfile.mkdtemp(prefix="deck-site-")
    r = subprocess.run(
        [sys.executable, os.path.join(ROOT, "tools", "site", "build.py"), tmp],
        capture_output=True, text=True)
    check("the site generator runs", r.returncode == 0,
          (r.stderr or r.stdout)[-500:])
    if r.returncode != 0:
        return 1

    built = []
    for dirpath, _dirs, files in os.walk(tmp):
        for fn in sorted(files):
            built.append(os.path.relpath(os.path.join(dirpath, fn), tmp))
    check("it produced pages", len(built) > 12, f"only {len(built)}")

    for relpath in sorted(built):
        live = os.path.join(DOCS, relpath)
        if not os.path.exists(live):
            check(f"docs/{relpath} is committed", False,
                  "run: python3 tools/site/build.py")
            continue
        with open(os.path.join(tmp, relpath), encoding="utf-8") as a, \
                open(live, encoding="utf-8") as b:
            check(f"docs/{relpath} matches the source", a.read() == b.read(),
                  "run: python3 tools/site/build.py")

    # ---- and now the links, against what is actually in docs/
    dead = []
    for relpath in sorted(p for p in built if p.endswith(".html")):
        page_dir = os.path.dirname(os.path.join(DOCS, relpath))
        with open(os.path.join(tmp, relpath), encoding="utf-8") as f:
            body = f.read()
        for href in links(body):
            if href.startswith(("http://", "https://", "#", "mailto:",
                                "data:")):
                continue
            target = os.path.normpath(os.path.join(page_dir,
                                                   href.split("#")[0]))
            if not os.path.exists(target):
                dead.append(f"{relpath} → {href}")
    check("every relative link resolves", not dead,
          "; ".join(dead[:6]) + (f" (+{len(dead) - 6} more)"
                                 if len(dead) > 6 else ""))

    # A generated site with Jekyll left on serves the HTML through a renderer
    # that mangles it. The marker file is one byte and its absence is silent.
    check(".nojekyll is present",
          os.path.exists(os.path.join(DOCS, ".nojekyll")),
          "Pages would run the generated HTML through Jekyll")

    shutil.rmtree(tmp, ignore_errors=True)
    if fails:
        print(f"\n{len(fails)} site check(s) failed")
        return 1
    print("\nsite checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
