// Generate core/fold_table.h — the character folding the deck applies before
// drawing (accents stripped, typographic punctuation squared off).
//
// Doing this by hand means guessing which characters NFKD actually decomposes.
// It is not obvious: é decomposes to e + a combining mark, but Æ, Ø, Ð, Þ and ß
// do not decompose at all and therefore fall through to a space. Rather than
// encode that folklore, run the real pipeline per codepoint and tabulate it.
//
//   node tools/gen_fold_table.js > core/fold_table.h

// The exact pipeline from deckText() in legacy/web/app.js.
function fold(ch) {
  return ch
    .normalize("NFKD").replace(/[̀-ͯ]/g, "")
    // Letters with no Unicode decomposition — NFKD leaves them alone, so
    // without this they fall through to a space and "Ágætis" reads "Ag tis".
    .replace(/Æ/g, "AE").replace(/æ/g, "ae")
    .replace(/Œ/g, "OE").replace(/œ/g, "oe")
    .replace(/Ø/g, "O").replace(/ø/g, "o")
    .replace(/Ð/g, "D").replace(/ð/g, "d")
    .replace(/Đ/g, "D").replace(/đ/g, "d")
    .replace(/Þ/g, "TH").replace(/þ/g, "th")
    .replace(/ß/g, "ss")
    .replace(/Ł/g, "L").replace(/ł/g, "l")
    .replace(/Ħ/g, "H").replace(/ħ/g, "h")
    .replace(/Ŋ/g, "NG").replace(/ŋ/g, "ng")
    .replace(/Ŧ/g, "T").replace(/ŧ/g, "t")
    .replace(/ı/g, "i").replace(/ĸ/g, "k")
    .replace(/[‘’ʼ′]/g, "'")
    .replace(/[“”″]/g, '"')
    .replace(/[–—−]/g, "-")
    .replace(/…/g, "...")
    .replace(/[^\x20-\x7e]/g, " ");
}

const LO = 0x80, HI = 0x24f;                  // Latin-1 Supplement + Extended-A/B
const EXTRA = [0x02bc, 0x2013, 0x2014, 0x2018, 0x2019, 0x201c, 0x201d,
               0x2026, 0x2032, 0x2033, 0x2212];

const rows = [];
for (let cp = LO; cp <= HI; cp++) rows.push([cp, fold(String.fromCodePoint(cp))]);
const extras = EXTRA.map((cp) => [cp, fold(String.fromCodePoint(cp))]);

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const table = rows.map(([cp, out]) =>
  `  "${esc(out)}",` + " ".repeat(Math.max(1, 10 - out.length)) +
  `/* U+${cp.toString(16).toUpperCase().padStart(4, "0")} */`).join("\n");
const extraTable = extras.map(([cp, out]) =>
  `  { 0x${cp.toString(16)}, "${esc(out)}" },`).join("\n");

const folded = rows.filter(([, o]) => o !== " ").length;

process.stdout.write(`/* GENERATED by tools/gen_fold_table.js — do not edit.
 * Source: the deckText() pipeline in legacy/web/app.js
 *
 * ${folded} of ${rows.length} codepoints in U+${LO.toString(16).toUpperCase()}..U+${HI.toString(16).toUpperCase()} fold to ASCII; the rest
 * have no decomposition and become a space, which is what the JS does too.
 * Codepoints outside these tables also become a space.
 */
#ifndef DECK_FOLD_TABLE_H
#define DECK_FOLD_TABLE_H

#include <stdint.h>

#define FOLD_LO 0x${LO.toString(16)}
#define FOLD_HI 0x${HI.toString(16)}

static const char *const FOLD_LATIN[FOLD_HI - FOLD_LO + 1] = {
${table}
};

typedef struct { uint32_t cp; const char *out; } fold_extra_t;

#define FOLD_EXTRA_N ${extras.length}
static const fold_extra_t FOLD_EXTRA[FOLD_EXTRA_N] = {
${extraTable}
};

#endif /* DECK_FOLD_TABLE_H */
`);
