// Generate core/dolphin_rom.h — the dolphin silhouette masks.
//
// The dolphins are bezier paths filled by Canvas and thresholded on alpha.
// There is no canvas in C, and reimplementing the rasteriser would not
// reproduce Canvas's antialiasing, so the shapes would drift. Instead drive
// real Chromium, call the EXISTING dolphinRaster() from legacy/web/dolphin.js
// over every quantised (length, angle, flex), and bake what it produces.
//
// Output is committed, so this only needs running if the silhouettes change.
//   node tools/gen_dolphin_rom.js > core/dolphin_rom.h
//
// Requires playwright-core and a Chromium at CHROMIUM (or the default below).

const fs = require("fs");
const path = require("path");
const { chromium } = require("playwright-core");

const ROOT = path.join(__dirname, "..");
const EXE = process.env.CHROMIUM || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";

// Lengths come from the pod in dolphin.js. Angles cover the full breach sweep
// with headroom; flex is the three-state tail cycle.
const LENGTHS = [30, 21];
const ANGLES = [];
for (let a = -90; a <= 90; a += 10) ANGLES.push(a);
const FLEX = [0, 1, 2];

(async () => {
  const browser = await chromium.launch({ executablePath: EXE });
  const page = await browser.newPage();
  await page.setContent("<canvas id=c></canvas>");
  await page.addScriptTag({
    content: fs.readFileSync(path.join(ROOT, "legacy", "web", "dolphin.js"), "utf8")
      .replace(/^function oceanFrame[\s\S]*$/m, ""),   // scene needs globals we lack
  });

  const out = await page.evaluate(({ LENGTHS, ANGLES, FLEX }) => {
    const res = [];
    for (const len of LENGTHS)
      for (const a of ANGLES)
        for (const flex of FLEX) {
          const r = dolphinRaster(len, a, flex);
          const bytes = [];
          for (let i = 0; i < r.w * r.h; i += 8) {
            let b = 0;
            for (let k = 0; k < 8 && i + k < r.w * r.h; k++)
              if (r.data[i + k]) b |= 1 << k;
            bytes.push(b);
          }
          res.push({ len, a, flex, w: r.w, h: r.h, bytes });
        }
    return res;
  }, { LENGTHS, ANGLES, FLEX });

  await browser.close();

  const total = out.reduce((n, r) => n + r.bytes.length, 0);
  let off = 0;
  for (const r of out) { r.off = off; off += r.bytes.length; }

  const bits = [];
  for (const r of out) bits.push(...r.bytes);
  const bitLines = [];
  for (let i = 0; i < bits.length; i += 16)
    bitLines.push("  " + bits.slice(i, i + 16).map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ") + ",");

  process.stdout.write(`/* GENERATED by tools/gen_dolphin_rom.js — do not edit.
 * Source: dolphinRaster() in legacy/web/dolphin.js, rasterised by real Chromium.
 *
 * ${out.length} silhouettes, ${total} bytes of bitmap. One bit per dot, LSB first,
 * rows packed continuously. Reproducing Canvas's bezier fill and alpha
 * threshold in C would not match, so the shapes are baked rather than derived.
 */
#ifndef DECK_DOLPHIN_ROM_H
#define DECK_DOLPHIN_ROM_H

#include <stdint.h>

typedef struct {
  uint8_t  len, w, h, flex;
  int16_t  angle;
  uint32_t off;         /* into DOLPHIN_BITS */
} dolphin_mask_t;

#define DOLPHIN_N ${out.length}
#define DOLPHIN_BYTES ${total}

static const uint8_t DOLPHIN_BITS[DOLPHIN_BYTES] = {
${bitLines.join("\n")}
};

/* len, angle, flex, w, h, bit offset */
static const dolphin_mask_t DOLPHIN_MASKS[DOLPHIN_N] = {
${out.map((r) =>
  `  { ${r.len}, ${r.w}, ${r.h}, ${r.flex}, ${String(r.a).padStart(3)}, ${r.off} },`
).join("\n")}
};

#endif /* DECK_DOLPHIN_ROM_H */
`);
})();
