// Generate core/font_rom.h from the legacy JS font ROMs.
//
// Transcribing 90-odd glyphs by hand is a great way to introduce a silent
// one-bit error, so don't: read legacy/web/font.js and emit the C tables.
// The ASCII tables bake in the JS lookup rules — toUpperCase, and the
// "unknown char" fallbacks — so the C side needs neither.
//
//   node tools/gen_font_rom.js > core/font_rom.h

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const SRC = path.join(__dirname, "..", "legacy", "web", "font.js");
const js = fs.readFileSync(SRC, "utf8") +
  ";globalThis.__F5 = FONT5; globalThis.__F3 = FONT3;";
const ctx = { globalThis: null };
ctx.globalThis = ctx;
vm.createContext(ctx);
vm.runInContext(js, ctx);
const { __F5: FONT5, __F3: FONT3 } = ctx;

const LO = 0x20, HI = 0x7e;
const hex = (n) => "0x" + n.toString(16).padStart(2, "0");

function asciiTable(font, fallbackKey, rows) {
  const out = [];
  for (let c = LO; c <= HI; c++) {
    const ch = String.fromCharCode(c).toUpperCase();   // JS uppercases first
    const g = font[ch] || font[fallbackKey];           // ...then falls back
    out.push({ c, ch: String.fromCharCode(c), g });
  }
  return out.map(({ c, ch, g }) => {
    const label = ch === "\\" ? "backslash" : ch === " " ? "space" : ch;
    return `  { ${g.slice(0, rows).map(hex).join(", ")} },` +
           ` /* ${hex(c)} ${label} */`;
  }).join("\n");
}

function specialTable(font, rows) {
  const keys = Object.keys(font).filter((k) => k.codePointAt(0) > 127);
  if (!keys.length) return "  { 0, { 0 } }";
  return keys.map((k) => {
    const g = font[k].slice(0, rows).map(hex).join(", ");
    return `  { 0x${k.codePointAt(0).toString(16)}, { ${g} } },` +
           ` /* ${k} */`;
  }).join("\n");
}

const n5 = Object.keys(FONT5).filter((k) => k.codePointAt(0) > 127).length;
const n3 = Object.keys(FONT3).filter((k) => k.codePointAt(0) > 127).length;

process.stdout.write(`/* GENERATED by tools/gen_font_rom.js — do not edit.
 * Source: legacy/web/font.js
 *
 * ASCII tables cover 0x20..0x7e and already encode the JS lookup rules:
 * lowercase is folded to uppercase, and characters the ROM lacks resolve to
 * '?' (5x7) or blank (3x5). Codepoints above 127 live in the specials tables.
 */
#ifndef DECK_FONT_ROM_H
#define DECK_FONT_ROM_H

#include <stdint.h>

#define FONT_ASCII_LO 0x20
#define FONT_ASCII_HI 0x7e
#define FONT_ASCII_N  (FONT_ASCII_HI - FONT_ASCII_LO + 1)

typedef struct { uint32_t cp; uint8_t rows[7]; } font5_special_t;
typedef struct { uint32_t cp; uint8_t rows[5]; } font3_special_t;

/* 5x7: 7 rows, 5 bits each, MSB = leftmost column (bit 0x10). */
static const uint8_t FONT5_ASCII[FONT_ASCII_N][7] = {
${asciiTable(FONT5, "?", 7)}
};

#define FONT5_SPECIAL_N ${n5}
static const font5_special_t FONT5_SPECIAL[FONT5_SPECIAL_N] = {
${specialTable(FONT5, 7)}
};

/* 3x5: 5 rows, 3 bits each, MSB = leftmost column (bit 0x4). */
static const uint8_t FONT3_ASCII[FONT_ASCII_N][5] = {
${asciiTable(FONT3, " ", 5)}
};

#define FONT3_SPECIAL_N ${n3}
static const font3_special_t FONT3_SPECIAL[FONT3_SPECIAL_N] = {
${specialTable(FONT3, 5)}
};

#endif /* DECK_FONT_ROM_H */
`);
