#!/usr/bin/env python3
"""Turn vehicles/*.json into docs/VEHICLES.md.

    python3 tools/vehicles/build.py [outfile]

Generated for the same reason the diagrams and the pictures are: a fitment
table maintained by hand goes stale the first time somebody adds a car and
edits only half the places it appears. Here, adding a car is adding one file.

The output is deliberately not a single flat table. A flat table has to pick
one row shape for every car, and the interesting information is exactly the
part that does not fit — the MX-5 ND has no aperture at all, the NC is the only
one of nine with steering-wheel controls, and the S2000's answer to half the
questions is "it does not have that". So there is a comparison table for the
things every car genuinely shares, and then a section per car for everything
else.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "vehicles")

MARK = {"verified": "✅", "unverified": "⚠️", "measure": "📏"}

# Order matters: it is the order somebody works through when buying.
FIELDS = [
    ("fits", "Does the deck fit"),
    ("aperture", "Aperture"),
    ("depth_mm", "Depth behind the dash"),
    ("fascia_adapter", "Fascia"),
    ("harness", "Harness adapter"),
    ("aerial", "Aerial adapter"),
    ("swc", "Steering-wheel controls"),
    ("illumination", "Dash dimmer"),
    ("ignition", "Switched live"),
]

LIST_FIELDS = [
    ("same_as_other_generations", "Same as the other generations"),
    ("differs_from_ap1", "Differs from the AP1"),
    ("differs_from_ap2", "Differs from the AP2"),
    ("differs_from_na", "Differs from the NA"),
    ("market_notes", "By market"),
    ("gotchas", "Gotchas"),
]


def load():
    cars = []
    for dirpath, _dirs, files in os.walk(SRC):
        for fn in sorted(files):
            if fn.endswith(".json"):
                p = os.path.join(dirpath, fn)
                with open(p, encoding="utf-8") as f:
                    d = json.load(f)
                d["_path"] = os.path.relpath(p, ROOT)
                cars.append(d)
    # brand, then model, then the order the generations were built — which is
    # the file order, so sort on the path rather than on the generation name.
    cars.sort(key=lambda c: (c["brand"], c["model"], c["_path"]))
    return cars


def mark(field):
    """'⚠️ value' — but not '⚠️ ⚠️ value'.

    A field whose text already opens with a warning is emphasising something
    beyond its confidence level, and stacking the automatic marker on top of
    the author's makes the table look like a bug."""
    v = field["v"]
    m = MARK[field["c"]]
    return v if v.startswith(tuple(MARK.values())) else f"{m} {v}"


def anchor(c):
    return f"{c['brand']}-{c['model']}-{c['generation']}".lower() \
        .replace(" ", "-").replace(".", "").replace("/", "")


def render(cars):
    o = []
    w = o.append
    w("# Vehicles\n")
    w("**Generated** from `vehicles/*.json` by `tools/vehicles/build.py`. "
      "Do not edit this file — edit the car and rerun.\n")
    w("---\n")
    w("## The deck does not change. Only the adapters do.\n")
    w("Every car below takes the same deck: the same ESP32, the same panel, "
      "the same DAC, mux, tuner and firmware, built to the one shopping list "
      "in [BUILD.md](BUILD.md). It fits an **ISO 7736** aperture and speaks "
      "**ISO 10487**, and those two standards are the entire reason a "
      "home-built head unit drops into anything.\n")
    w("What varies is a bag of adapters — something to fill the hole, "
      "something to reach the car's connector, something to reach its aerial "
      "— and how much room is behind the dash.\n")
    w("> ### The one people get backwards\n>\n"
      "> **The radio region follows where you drive, not where the car was "
      "built.** A JDM import in Britain receives British stations, so it wants "
      "the European band plan. Everything *else* about fitting an import "
      "follows the car's market.\n>\n"
      "> It is not a subtle failure. Japan's FM band is 76–95 MHz against "
      "Europe's 87.5–108, so a European deck driven in Japan can tune about a "
      "tenth of the band. The Americas use 10 kHz AM spacing against 9 kHz "
      "elsewhere, and on the wrong step every station lands between channels. "
      "The deck stores the region in NVS and it is set once — see "
      "`deck_tuner_region_set()`.\n")

    w("## Confidence\n")
    w("| | Means |")
    w("|---|---|")
    w("| ✅ | Checked against a datasheet, a standard, or a fact not in "
      "dispute |")
    w("| ⚠️ | Believed true and **not confirmed** — check before buying |")
    w("| 📏 | Varies car to car. Measure yours; do not trust any list, "
      "including this one |")
    w("")
    w("**There are no retailer part numbers here on purpose.** They change, "
      "they are regional, they go out of stock, and a stale one looks "
      "authoritative. What you get is the thing to search for, which does not "
      "go stale.\n")

    # ---- the comparison table, on the three questions every car answers
    w("---\n")
    w("## At a glance\n")
    w("| Car | Years | Fits? | Aperture | Wheel controls |")
    w("|---|---|---|---|---|")
    for c in cars:
        name = f"[{c['brand']} {c['model']} {c['generation']}](#{anchor(c)})"
        fits = c["fits"]
        swc = c["swc"]
        w(f"| {name} | {c['years']} | {mark(fits)} | {mark(c['aperture'])} "
          f"| {mark(swc)} |")
    w("")

    # ---- one section per car
    for c in cars:
        w("---\n")
        w(f"## {c['brand']} {c['model']} {c['generation']}\n")
        aka = c.get("also_known_as") or []
        w(f"**{c['years']}**"
          + (f" · also known as {', '.join(aka)}" if aka else "")
          + f" · markets: {', '.join(c['markets'])}\n")
        w(f"<sub>`{c['_path']}`</sub>\n")

        w("| | | |")
        w("|---|---|---|")
        for key, label in FIELDS:
            f = c[key]
            why = f.get("why") or ""
            w(f"| **{label}** | {mark(f)} | {why} |")
        w("")

        for key, label in LIST_FIELDS:
            items = c.get(key)
            if not items:
                continue
            w(f"**{label}**\n")
            for it in items:
                w(f"- {it}")
            w("")

    w("---\n")
    w("## Adding a car\n")
    w("Copy the nearest file in `vehicles/`, change what differs, run "
      "`python3 tools/vehicles/build.py`, and open a pull request. If a field "
      "does not apply — many cars have no steering-wheel controls at all — say "
      "so explicitly rather than leaving it out. \"None fitted\" is "
      "information; a missing key is not.\n")
    w("`tools/verify/test_vehicles.py` checks that every file has every field "
      "and that no claim is left without a confidence marker.\n")
    return "\n".join(o) + "\n"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "docs",
                                                             "VEHICLES.md")
    cars = load()
    if not cars:
        sys.exit("no vehicles found under " + SRC)
    with open(out, "w", encoding="utf-8") as f:
        f.write(render(cars))
    print(f"  {os.path.relpath(out, ROOT):<28} {len(cars)} vehicles, "
          f"{os.path.getsize(out) / 1024:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
